### ISSUE TITLE
Freezing in Looks Menu

### ISSUE THREAD

**Issue by DeleteRepeat** [LaughingHyena279/FO4NSFW#4]
I am having an issue with the game freezing in the looks menu when attempting to remove clothes. I have tried doing this through console commands too. No luck.

**Comment by DeleteRepeat** [comment]
Was able to get looks menu to look after getting the pipboy and unequipping clothes manually.

**Comment by LaughingHyena279** [comment]
This is a known issue with Looks Menu, and there is no fix for it.

**Comment by DeleteRepeat** [comment]
"It just works!" - Todd Howard
