### ISSUE TITLE
Unable to Download "A Forest"

### ISSUE THREAD

**Issue by SirJellyNips** [LaughingHyena279/FO4NSFW#9]
Can't download the mod, because the mod doesn't exist anymore.

**Comment by TheNygaard** [comment]
Had same issue, download it from here: https://mega.nz/file/fd9iXSAK#f3CyZyf-ngT5IZ6zunm2rzOyFLaLeZELi49Q4GGlBj0 

Close wabbajack.
And place it in the "downloads" folder.
Start wabbajack.
Done.

Note: I found the link here:
https://github.com/wabbajack-tools/opt-out-lists/blob/master/ServerWhitelist.yml

**Comment by LaughingHyena279** [comment]
New link is the one you want to use, posted above. Closing this as resolved.
